FROM resin/rpi-raspbian:jessie

RUN apt-get -qy update && apt-get install \
	git python3 python3-flask python3-werkzeug
	
RUN apt-get -qy install nmap iproute2 cron

CMD /var/server/update-hosts.sh && cron && tail -f /dev/null
