version: '2'

services:
    grafana:
        image: fg2it/grafana-armhf:v3.1.1
    nginxhost:
        image: ckulka/rpi-nginx
        environment:
          - NGINX_NO_UPDATE=1
        ports:
          - "80:80"
        volumes:
          - ./nginxconfig/:/etc/nginx/sites-enabled
          - /var/www/html:/var/www/html
        networks:
          - backend
          - frontend

    buildserver:
        build:
            context: .
            dockerfile: Dockerfile.build-server
        volumes:
          - ./cbd/build-server/:/var/server
          - buildstore:/var/server/store
        networks:
          - backend
     
    hostdisco:
        build:
            context: .
            dockerfile: Dockerfile.host-discovery
        volumes:
          - ./host-discovery/:/var/server
          - hoststore:/var/server/store
        networks:
          - backend
    
    hostscanner:
        build:
            context: .
            dockerfile: Dockerfile.host-scanner
        volumes:
          - ./host-discovery/:/var/server
          - hoststore:/var/server/store
        network_mode: "host"
    jenkins:
        build:
            context: .
            dockerfile: Dockerfile.jenkins
        ports:
          - "8080:8080"
        network_mode: "host"
        volumes:
          - jenkins_store:/var/jenkins_home

volumes:
    hoststore:
        driver: local
    buildstore:
        driver: local
    jenkins_store:
        driver: local
        
networks:
     frontend:
        driver: bridge
     backend:
        driver: bridge
