FROM dilgerm/rpi-jenkins

USER root
RUN apt-get -qy update && apt-get -qy install unzip git mercurial

RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

COPY jenkinsconfig/plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt

COPY jenkinsconfig/*.groovy /usr/share/jenkins/ref/init.groovy.d/
COPY jenkinsconfig/*.properties $JENKINS_HOME/

USER jenkins
WORKDIR /
CMD ["/bin/bash","--","/usr/local/bin/jenkins.sh"]
